- .github/workflows/docs-pr.yml
- .github/workflows/docs-push.yml
This is a straight copy of the same files from the `ansible.windows` collections, with only this line having the collection name updated:
```yaml
if: github.repository == 'ansible-collections/microsoft.ad'
```
> add docs build workflows

- docs/docsite/rst/guide_attributes.rst
- docs/docsite/rst/guide_migration.rst
- plugins/modules/computer.py
- plugins/modules/domain.py
- plugins/modules/domain_controller.py
- plugins/modules/membership.py
- plugins/modules/object_info.py
- plugins/modules/ou.py
- plugins/modules/user.py
Rather than describe the changes here, I tried to keep them grouped in the commits themselves, so please see those for individual changes (and we can revert some if opinions differ).
> Update some relatively small docs stuff

- docs/docsite/rst/guide_attributes.rst
- plugins/module_utils/_ADObject.psm1
- plugins/modules/object.ps1
- tests/integration/targets/object/tasks/main.yml
- tests/integration/targets/object/tasks/tests.yml
Create mock attributes for the test to actually test the various known types. This expands the tests but also brought up some errors in the previous logic which has now been fixed.
microsoft.ad.object
> Expand tests for attributes and the various types

- CHANGELOG.rst
- changelogs/changelog.yaml
Prepare for the v1.0.0 release.
microsoft.ad
> Prepare for v1.0.0 release

- README.md
Add docs around the release policy and fix up minor copy and pastes.
README
> Add release policy to readme

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/user-password-expired.yml
Preparation for the v1.1.0 release.
microsoft.ad
> Prepare for v1.1.0 release

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/group-case-sensitivity-check.yml
- changelogs/fragments/group-domainlocal-scopeinfo.yml
- changelogs/fragments/ldap-env-var.yml
- changelogs/fragments/ldap-laps-decryption.yml
- changelogs/fragments/server2012.yml
- galaxy.yml
Release 1.2.0 preparations.
microsoft.ad
> Prepare for v1.2.0 release

- .azure-pipelines/azure-pipelines.yml
Bump testing to use the newly branched stable-2.16 branch and ensure devel has 2.17 ignores.
microsoft.ad
> Start testing with Ansible 2.17/devel

- .azure-pipelines/azure-pipelines.yml
- README.md
- changelogs/fragments/ansible_support.yml
- galaxy.yml
- meta/runtime.yml
Bumps the minimum Ansible version and cleans up some pslint ignores now that we can.
microsoft.ad
> Set new supported ansible minimum version to 2.14

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/73-import-activedirectory-module.yml
- changelogs/fragments/ansible_support.yml
- changelogs/fragments/search-by-identity.yml
Preparation for the v1.4.0 release.
microsoft.ad
> Prepare for v1.4.0 release

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/debug_ldap_client-failure.yml
- galaxy.yml
Preparations for the v1.4.1 release.
microsoft.ad
> Prepare for v1.4.1 release

- plugins/doc_fragments/ad_object.py
- plugins/modules/computer.py
- plugins/modules/domain.py
- plugins/modules/domain_controller.py
- plugins/modules/group.py
- plugins/modules/membership.py
- plugins/modules/object.py
- plugins/modules/object_info.py
- plugins/modules/offline_join.py
- plugins/modules/ou.py
- plugins/modules/user.py
Update the module docs to try and simplify the the name/identity/path options, for example what they represent and when they should be used. Also update the documentation to reflect how these modules should be run on a Windows target.
Fixes: https://github.com/ansible-collections/microsoft.ad/issues/85
Fixes: https://github.com/ansible-collections/microsoft.ad/issues/86
Fixes: https://github.com/ansible-collections/microsoft.ad/issues/87
microsoft.ad.*
> Update module documentation

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/default_options.yml
- changelogs/fragments/group-support-long-group-names.yml
- changelogs/fragments/membership-invalid-ou.yml
- changelogs/fragments/templating_support.yml
Preparations for the v1.5.0 release.
microsoft.ad
> Prepare for v1.5.0 release

- plugins/doc_fragments/ldap_connection.py
This adds docs for the `dpapi-ng` Python requirement when dealing with LAPS decryption.
> Document LAPS decryption Python requirement

- .azure-pipelines/azure-pipelines.yml
- galaxy.yml
Devel has been bumped to 2.18 so this aligns with the new version there.
microsoft.ad
> Bump devel version to 2.18 and add 2.17 sanity

- .ansible-lint
- plugins/inventory/ldap.py
- plugins/modules/computer.py
- plugins/modules/domain_controller.py
- plugins/modules/group.py
- plugins/modules/object.py
- plugins/modules/object_info.py
- plugins/modules/user.py
- tests/utils/shippable/lint.sh
Updates to latest version of lint used by the galaxy import tests and fix new violations.
microsoft.ad
> Upgrade ansible-lint and fix problems

- plugins/modules/domain_controller.py
Updated example using a non existing plugin microsoft.ad.win_reboot. Changed to ansible.windows.win_reboot
domain_controller.py
```paste below
```
> Update domain_controller.py documentation

- tests/sanity/ignore-2.18.txt
Now that https://github.com/ansible/ansible/pull/83325/ is merged we no longer need to ignore this check for devel+.
microsoft.ad
> Remove no longer needed sanity ignore

- .azure-pipelines/azure-pipelines.yml
Try to fix the CI coverage run and make it easier to rerun failed groups.
Testing
> Fix CI to have coverage name

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/0-readme.yml
- changelogs/fragments/124-computer-identity-dollar.yml
- changelogs/fragments/130-group-member.yml
- changelogs/fragments/141-group-empty-member.yml
- changelogs/fragments/ansible-version.yml
- changelogs/fragments/computer-sam.yml
- changelogs/fragments/datetime-utc-deprecation.yml
- changelogs/fragments/ldap-msa.yml
- changelogs/fragments/membership-rename.yml
- changelogs/fragments/membership-server.yml
- changelogs/fragments/reboot_timeout.yml
Preparations for the v1.7.0 release.
Release
> Prepare for v1.7.0 release

- README.md
- docs/docsite/links.yml
As a part of https://forum.ansible.com/t/proposal-consolidating-ansible-discussion-platforms/6812
If the channel is still super popular, feel free to update it with a Matrix channel if exists or just with removing the ML
README.md
> README: remove IRC

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/debug-ldap-client-doc.yml
- galaxy.yml
v1.7.1 preparation PR.
microsoft.ad
> Prepare for v1.7.1 release

- .azure-pipelines/azure-pipelines.yml
- changelogs/fragments/win-2025.yml
- plugins/modules/domain.yml
- plugins/modules/domain_child.yml
- tests/integration/targets/domain/tasks/main.yml
- tests/integration/targets/inventory_ldap/roles/test/tasks/main.yml
Adds Windows Server 2025 to the test matrix and official support.
> Add support for Windows Server 2025

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/replication-dc.yml
- changelogs/fragments/user-permissions-handling.yml
- changelogs/fragments/win-2025.yml
Preparation for the v1.8.0 release.
release
> Prepare release v1.8.0

- CHANGELOG.rst
- changelogs/changelog.yaml
- galaxy.yml
Release preparation for v1.0.1
> Prepare for v1.8.1 release

- .azure-pipelines/azure-pipelines.yml
- .azure-pipelines/commands/lint.sh
- .gitignore
- changelogs/fragments/ldap-dt.yml
- docs/docsite/rst/guide_ldap_inventory.rst
- plugins/inventory/ldap.py
- tests/integration/targets/inventory_ldap/roles/test/tasks/invoke.yml
- tests/integration/targets/inventory_ldap/roles/test/tasks/main.yml
- tests/requirements.yml
Fixes after DT changes in Ansible 2.19
> Test fixes after DT merge - ci_complete

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/ansible-ver.yml
- changelogs/fragments/ldap-dt.yml
Release preparation for the v1.9.0 release.
> Prepare for v1.9.0 release

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/laps-templating.yml
- galaxy.yml
Release preparation for v1.9.1.
> Prepare for v1.9.1 release

- tests/integration/targets/computer/tasks/tests.yml
- tests/integration/targets/domain_child/tasks/cross_domain.yml
- tests/integration/targets/object/tasks/tests.yml
- tests/integration/targets/ou/tasks/tests.yml
- tests/integration/targets/user/tasks/tests.yml
Fixes test assertions after multi value attribute bugfix.
> Fix test assertions after bugfix - ci_complete

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/correctly-return-multivalued-attributes-with-one-entry-as-array-instead-of-string.yml
- galaxy.yml
Release preparation for v1.9.2.
> Prepare for v1.9.2 release
