ansible-collections/microsoft.ad

docs/docsite/rst/guide_migration.rst, plugins/doc_fragments/ad_object.py, plugins/module_utils/_ADObject.psm1, plugins/modules/computer.py, plugins/modules/domain.py, plugins/modules/domain_controller.py, plugins/modules/group.ps1, plugins/modules/group.py, plugins/modules/membership.py, plugins/modules/object.py, plugins/modules/object_info.ps1, plugins/modules/object_info.py, plugins/modules/ou.py, plugins/modules/user.py, tests/integration/targets/group/aliases, tests/integration/targets/group/meta/main.yml, tests/integration/targets/group/tasks/main.yml, tests/integration/targets/group/tasks/tests.yml, tests/integration/targets/object_info/tasks/main.yml
Adds the `microsoft.ad.group` module which implements the same functionality of `community.windows.win_domain_group` and `community.windows.win_domain_group_membership`. Also adds the `groupType_AnsibleFlags` return value for `microsoft.ad.object_info` to more easily parse the `groupType` values it can return.
- New Module Pull Request
group
object_info
=> Added group module and object_info groupType handler

plugins/modules/computer.ps1, plugins/modules/computer.py, plugins/modules/object_info.ps1, plugins/modules/object_info.py, plugins/modules/user.py, tests/integration/targets/computer/tasks/tests.yml, tests/integration/targets/object_info/tasks/main.yml
Adds a few more common options to `microsoft.ad.computer`. Also adds user friendly flags when retrieving the `msDS-SupportedEncryptionTypes` attribute with `microsoft.ad.object_info`.
microsoft.ad.computer
microsoft.ad.object_info
=> Add extra options for computer and enc types to object_info

CHANGELOG.rst, CODE_OF_CONDUCT.md, changelogs/config.yaml, codecov.yml, galaxy.yml, plugins/module_utils/_ADObject.psm1
Updates various files to fit the collection inclusion requirements for the `ansible` package. Does relicense the _ADObject module util to GPL but as I'm currently the only author there I am happy to change it.
microsoft.ad
=> Update various files to fit collection template

docs/docsite/extra-docs.yml, docs/docsite/rst/guide_list_values.rst, docs/docsite/rst/guide_migration.rst, meta/runtime.yml, plugins/module_utils/_ADObject.psm1, plugins/modules/computer.ps1, plugins/modules/computer.py, plugins/modules/user.ps1, plugins/modules/user.py, tests/integration/targets/computer/tasks/tests.yml, tests/integration/targets/domain_controller/setup.yml, tests/integration/targets/membership/setup.yml, tests/integration/targets/object/tasks/tests.yml, tests/integration/targets/object_info/tasks/main.yml, tests/integration/targets/user/tasks/tests.yml
This PR makes sure all module options that manage LDAP attributes with multiple values use the subdict with add, remove, or set keys. It also adds a simple guide on how these values work and updates the migration page where it affected older modules.
microsoft.ad
=> Create common list option style

plugins/modules/user.py
Adds more examples of when `identity` would be used.
Fixes: https://github.com/ansible-collections/microsoft.ad/issues/26
=> Add more docs on user identity

docs/docsite/rst/guide_attributes.rst
The datetime value here is missing the minute offset portion needed.
Fixes: https://github.com/ansible-collections/microsoft.ad/issues/24
microsoft.ad
=> Fix up incorrect datetime tz offset example

changelogs/fragments/user-password-expired.yml, plugins/modules/user.ps1, tests/integration/targets/user/tasks/tests.yml
The `password_expired` for the `user` module did not have a custom action for when a user was being created. This fixes up that behaviour so the flag is set properly and adds a test for this scenario.
Fixes: https://github.com/ansible-collections/microsoft.ad/issues/25
=> Fix up password_expired on new user

changelogs/fragments/group-case-sensitivity-check.yml, plugins/modules/group.ps1, tests/integration/targets/group/tasks/tests.yml
Check the `category` and `group` options with a case insensitive match as they are enum values and not literal attribute values.
Fixes: https://github.com/ansible-collections/microsoft.ad/issues/31
microsoft.ad.group
=> group - check scope and category with a case insensitive check

tests/integration/targets/inventory_ldap/roles/test/tasks/main.yml
This test originally worked when merged but it seems like a recent Windows Update has disabled this scenario. I cannot figure out why it's happening or if there is a fix so will disable the test. In a real world scenario people should just use LDAPS instead of LDAP + StartTLS.
=> Disable LDAP StartTLS and cert auth test

changelogs/fragments/ldap-env-var.yml, plugins/doc_fragments/ldap_connection.py, tests/integration/targets/inventory_ldap/roles/test/tasks/main.yml
Expose the LDAP connection and authentication options used in the inventory plugin microsoft.ad.ldap through environment variables.
Fixes: https://github.com/ansible-collections/microsoft.ad/issues/34
=> Expose LDAP connection options in the environment

changelogs/fragments/group-domainlocal-scopeinfo.yml, plugins/module_utils/_ADObject.psm1, tests/integration/targets/group/tasks/tests.yml
Fix up the generic ADObject check for attributes with falsey values like 0, empty string, empty array/list. This was easily seen by using group with scope: domainlocal as the enum value for that scope is 0.
Fixes: https://github.com/ansible-collections/microsoft.ad/issues/31
_ADObject.psm1
=> Fix up AD attribute checks for falsey values

.azure-pipelines/azure-pipelines.yml, changelogs/fragments/server2012.yml
Remove 2012 and 2012 R2 from CI tests. This lines up with the removal of 2012 and 2012 R2 in the `ansible.windows` and `community.windows` collections and the dropping of support in Ansible 2.16.
microsoft.ad
=> Remove 2012 and 2012 R2 from CI tests

changelogs/fragments/dpapi-req.yml, requirements.txt
The `dpapi-ng` optional requirement was added in 1.2.0 but the dependency wasn't declared in the EE requirements.txt file. This PR adds this requirement so people who build an EE image will get this feature by default.
microsoft.ad
=> Add dpapi-ng to Python requirements file

changelogs/fragments/protect-from-deletion.yml, plugins/module_utils/_ADObject.psm1, tests/integration/targets/computer/tasks/tests.yml, tests/integration/targets/user/tasks/tests.yml
The code for handling `protect_from_deletion` when creating new objects would only work if the cmdlet used contained the `-ProtectedFromAccidentalDeletion` parameter. Cmdlets like `New-ADUser`, `New-ADGroup`, `New-ADComputer` do not have this parameter so handling for this needed to happen after the object is created with the `Set-ADObject` cmdlet.
Fixes: https://github.com/ansible-collections/microsoft.ad/issues/47
module_utils/_ADObject.psm1
=> Fix up protect from accidental deletion on new objects

changelogs/fragments/ldap-filter-raw.yml, galaxy.yml, plugins/inventory/ldap.py
Adds the new option filter_without_computer to control whether the AND clause objectClass=computer is added to the final filter used or not. While not needed for normal Active Directory environments this does allow different environments to be used as the LDAP source.
Fixes: https://github.com/ansible-collections/microsoft.ad/issues/55
=> ldap inventory add filter_without_computer

changelogs/fragments/move-adparams.yml, plugins/module_utils/_ADObject.psm1
Two cmdlets were missing the `@adParams` splat which contained the `domain_server` and `domain_username/password` values. This PR adds that splatted variable to those calls.
Fixes: https://github.com/ansible-collections/microsoft.ad/issues/54
microsoft.ad._ADObject
=> Fix up missing common AD parameters on some cmdlets

changelogs/fragments/default-path.yml, plugins/doc_fragments/ad_object.py, plugins/module_utils/_ADObject.psm1, tests/integration/targets/object/tasks/tests.yml, tests/integration/targets/user/tasks/tests.yml
Changes the behaviour of path for existing objects when no path was specified and identity points to a valid object. The old behaviour was to treat no path value as the default container for that object type which would have resulted in moving the object. The new behaviour will treat no path or empty path value as keep the existing path. The object will only be moved if an explicit path value was set.
Adds support for the sentinel value microsoft.ad.default_path to be specified as the path which will be the default container for that object type.
Fixes: https://github.com/ansible-collections/microsoft.ad/issues/43
Fixes: https://github.com/ansible-collections/microsoft.ad/issues/44
Fixes: https://github.com/ansible-collections/microsoft.ad/issues/52
Fixes: …
=> Change default path handling for existing AD objs

changelogs/fragments/datetime-attributes.yml, changelogs/fragments/user-account-expired-password.yml, changelogs/fragments/user-spn-diff.yml, plugins/module_utils/_ADObject.psm1, plugins/modules/user.ps1, plugins/modules/user.py, tests/integration/targets/user/tasks/tests.yml
Fixes the idempotent comparisons of date_time values. Also fixes a few problems with the user module around diff output and handling of expired accounts.
Fixes: https://github.com/ansible-collections/microsoft.ad/issues/57
=> Fix datetime comparisons and other user checks

CHANGELOG.rst, README.md, changelogs/changelog.yaml, changelogs/fragments/datetime-attributes.yml, changelogs/fragments/default-path.yml, changelogs/fragments/dpapi-req.yml, changelogs/fragments/ldap-filter-raw.yml, changelogs/fragments/move-adparams.yml, changelogs/fragments/protect-from-deletion.yml, changelogs/fragments/user-account-expired-password.yml, changelogs/fragments/user-spn-diff.yml
Preparations for the v1.3.0 release.
microsoft.ad
=> Prepare for v1.3.0 release

plugins/inventory/ldap.py
The code indicates the filename should be that the path ends in `microsoft.ad.ldap.yml` or `microsoft.ad.ldap.yaml`.
Resolves #67 
=> Docstring Does Match Code

changelogs/fragments/73-import-activedirectory-module.yml, plugins/modules/object_info.ps1, plugins/modules/object_info.py
This proposed change, add explicit import of ActiveDirectory module in object_info.
object_info
This change allow this module to run on server with automatic import of modules disabled. And improve error message when ActiveDirectory module is missing.
=> feat(object_info): add activedirectory module import

changelogs/fragments/search-by-identity.yml, plugins/doc_fragments/ad_object.py, plugins/module_utils/_ADObject.psm1, tests/integration/targets/user/tasks/tests.yml
Allows using the identity module option if no name was specified. Currently name must be set with state=present but identity will be used if no name was specified.
Tests still need to be added.
Fixes: https://github.com/ansible-collections/microsoft.ad/issues/74
_ADObject.psm1
=> Make name optional

changelogs/fragments/debug_ldap_client-failure.yml, plugins/action/debug_ldap_client.py
Ensure debug_ldap_client does not fail with a traceback when failing to get the krb5 context or default ccache. A failure in those steps should be reported in the output.
microsoft.ad.debug_ldap_client
=> Fix debug_ldap_client tracebacks

.vscode/settings.json, docs/docsite/rst/guide_ldap_inventory.rst, galaxy.yml, plugins/filter/dn_escape.yml, plugins/filter/ldap_converters.py, plugins/filter/parse_dn.yml, plugins/inventory/ldap.py, tests/integration/targets/inventory_ldap/roles/test/tasks/main.yml, tests/unit/plugins/filter/test_ldap_converters.py
Adds filters that can be used to escape values for use inside a DN attribute value and to parse a DN string into a more structured object. These filters are useful with the `microsoft.ad.ldap` inventory plugin as well as when forming values like the `path` or other DN attributes.
microsoft.ad.dn_escape
microsoft.ad.parse_dn
=> Add dn_escape and parse_dn filters

changelogs/fragments/membership-invalid-ou.yml, plugins/modules/membership.ps1, tests/integration/targets/membership/ansible.cfg, tests/integration/targets/membership/tasks/main.yml
Adds a helpful hint to the end of the error message when failing to join a domain due to an invalid/missing domain_ou_path.
Fixes: https://github.com/ansible-collections/microsoft.ad/issues/88
microsoft.ad.membership
=> Add error message for invalid domain_ou_path

changelogs/fragments/group-support-long-group-names.yml, plugins/module_utils/_ADObject.psm1, tests/integration/targets/group/tasks/tests.yml
Support group membership with a group name that is longer than 20 characters.
Fixes: https://github.com/ansible-collections/microsoft.ad/issues/63
Fixes: https://github.com/ansible-collections/microsoft.ad/issues/94
microsoft.ad.group (but affects other modules doing membership lookups)
=> Support long group names

changelogs/fragments/default_options.yml, meta/runtime.yml, plugins/doc_fragments/ad_object.py, plugins/modules/object_info.py
Adds the module defaults group microsoft.ad.domain to allow setting common connection parameters for module that communicate with the domain controller.
Fixes: https://github.com/ansible-collections/microsoft.ad/issues/93
microsoft.ad
=> Add module defaults group

changelogs/fragments/templating_support.yml, plugins/doc_fragments/ldap_connection.py, plugins/inventory/ldap.py, tests/integration/targets/inventory_ldap/roles/test/tasks/main.yml
Hello,
This PR contains some modifications in order to suppor Jinja2 templating in ldap inventory.
I have to to target an inventory directory to multiple Active Directory so I can't use environment variables.
```bash
$ tree inventory/
inventory/
├── 00_ad1.microsoft.ad.ldap.yml
├── 00_ad2.microsoft.ad.ldap.yml
├── 00_ad3.microsoft.ad.ldap.yml
└── 99_final.yml
```
I added a couple of lines in order to make connection options more dynamic and supporting Jinja2 templating as already implemented in other inventory plugins. 
```YAML
plugin: microsoft.ad.ldap
server: mydomain.local.lcl
port: 389
username: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=path/to/my/secret:ad_credential_user') }}@{{ lookup('community.hashi_vault.hashi_vault', …
```
=> Jinja2 templating support in inventory

changelogs/fragments/user-account-locked.yml, plugins/modules/user.ps1, tests/integration/targets/user/tasks/tests.yml
Ensure that creating a new user with an explicit account_locked value does not fail.
Fixes: https://github.com/ansible-collections/microsoft.ad/issues/108
=> microsoft.ad.user - Fix account_locked on creation

changelogs/fragments/membership-long-name.yml, plugins/modules/membership.ps1, tests/integration/targets/membership/tasks/main.yml
Fix issue with long computer hostnames.
Fixes #113 
microsoft.ad.membership
=> Fix for long computer names

plugins/action/domain_child.py, plugins/action/domain_controller.py, plugins/modules/domain.py, plugins/modules/domain_child.ps1, plugins/modules/domain_child.yml, plugins/modules/domain_controller.py, plugins/plugin_utils/_module_with_reboot.py, tests/integration/targets/domain_child/README.md, tests/integration/targets/domain_child/Vagrantfile, tests/integration/targets/domain_child/aliases, tests/integration/targets/domain_child/ansible.cfg, tests/integration/targets/domain_child/inventory.yml, tests/integration/targets/domain_child/setup.yml, tests/integration/targets/domain_child/tasks/main_child.yml, tests/integration/targets/domain_child/tasks/main_tree.yml, tests/integration/targets/domain_child/test.yml, tests/sanity/ignore-2.14.txt, tests/sanity/ignore-2.15.txt, tests/sanity/ignore-2.16.txt, tests/sanity/ignore-2.17.txt, tests/sanity/ignore-2.18.txt
Add the new module microsoft.ad.domain_child which can be used to create a child or tree domain in an existing forest.
Fixes: https://github.com/ansible-collections/microsoft.ad/issues/40
- New Module Pull Request
microsoft.ad.domain_child
=> Add domain_child module

.gitignore, changelogs/fragments/lookup-dn.yml, docs/docsite/extra-docs.yml, docs/docsite/rst/guide_ad_module_authentication.rst, docs/docsite/rst/guide_attributes.rst, docs/docsite/rst/guide_ldap_connection.rst, docs/docsite/rst/guide_migration.rst, plugins/doc_fragments/ad_object.py, plugins/module_utils/_ADObject.psm1, plugins/modules/computer.ps1, plugins/modules/computer.py, plugins/modules/group.ps1, plugins/modules/group.py, plugins/modules/ou.ps1, plugins/modules/ou.py, plugins/modules/user.ps1, plugins/modules/user.py, tests/integration/targets/computer/tasks/tests.yml, tests/integration/targets/domain_child/tasks/cross_domain.yml, tests/integration/targets/domain_child/test.yml, tests/integration/targets/group/tasks/tests.yml, tests/integration/targets/ou/tasks/tests.yml
Add a way to specify a custom server to lookup an AD identity on when using module options that accept a list of identities for an attribute. For example the microsoft.ad.group members option.
Also adds the domain_credentials option that is common to add AD based modules to specify credentials for the extra AD servers being contacted in case the default credentials do not work.
I need to find a good way to add a test for this, will most likely come under the tests done outside of CI as it will require multiple DC servers.
Fixes: https://github.com/ansible-collections/microsoft.ad/issues/56
Fixes: https://github.com/ansible-collections/microsoft.ad/issues/104
microsoft.ad.*
=> Add identity server lookup

changelogs/fragments/user-groups.yml, plugins/modules/user.ps1, plugins/modules/user.py, tests/integration/targets/domain_child/tasks/cross_domain.yml, tests/integration/targets/user/tasks/tests.yml
Adds the same DN lookup logic to the microsoft.ad.user groups option. This allows the caller to add/remove/set the user's group membership to groups that are in a different domain. This change also aligns renames the missing_behaviour option to lookup_failure_action to be consistent with the other lookup DN options. THe missing_behaviour option is still present as an alias for backwards compatibility.
=> microsoft.ad.user - Add group lookup DN logic

changelogs/fragments/membership-server.yml, plugins/modules/membership.ps1, plugins/modules/membership.py
Added the option domain_server to the microsoft.ad.membership module. This option allows the caller to specify the domain controller to use for domain join operations rather than have Windows lookup the DC for the domain specified.
Fixes: https://github.com/ansible-collections/microsoft.ad/issues/131#issuecomment-2201151651
microsoft.ad.membership
=> membership - Added domain_server option

changelogs/fragments/reboot_timeout.yml, plugins/doc_fragments/action_reboot.py, plugins/modules/domain.ps1, plugins/modules/domain.py, plugins/modules/domain_child.ps1, plugins/modules/domain_child.yml, plugins/modules/domain_controller.ps1, plugins/modules/domain_controller.py, plugins/modules/membership.ps1, plugins/modules/membership.py, plugins/plugin_utils/_module_with_reboot.py
Added the option reboot_timeout to modules that expose a reboot option. This provides a way for the caller to define a custom reboot timeout based on their environment specific details.
Fixes: https://github.com/ansible-collections/microsoft.ad/issues/78
microsoft.ad
=> Added common reboot_timeout option

changelogs/fragments/130-group-member.yml, plugins/module_utils/_ADObject.psm1, plugins/modules/group.ps1, tests/integration/targets/group/tasks/tests.yml
Implement fix for when trying to set group members on a group that is Builtin to the domain controller. This reverts the logic back to how it was before v1.6.0 so that setting these members continues to work.
Fixes: https://github.com/ansible-collections/microsoft.ad/issues/130
microsoft.ad.group
=> group - Fix setting members on builtin group

changelogs/fragments/124-computer-identity-dollar.yml, changelogs/fragments/computer-sam.yml, plugins/doc_fragments/ad_object.py, plugins/module_utils/_ADObject.psm1, plugins/modules/computer.ps1, plugins/modules/computer.py, tests/integration/targets/computer/tasks/tests.yml
Add extra logic to handle searching for a computer account by identity without the $ suffix. Also adds the ability to create a computer account without the $ suffix on the sAMAccountName attribute. This should be a niche scenario but it is useful for testing and is added for completion sakes.
Fixes: https://github.com/ansible-collections/microsoft.ad/issues/124
microsoft.ad.computer
=> computer - Improve sAMAccountName handling

plugins/module_utils/_ADObject.psm1, plugins/modules/service_account.ps1, plugins/modules/service_account.yml, tests/integration/targets/service_account/aliases, tests/integration/targets/service_account/meta/main.yml, tests/integration/targets/service_account/tasks/main.yml, tests/integration/targets/service_account/tasks/tests.yml
Adds the microsoft.ad.service_account module which can be used to manage service accounts like a group managed service account (gMSA). It is not possible to use the microsoft.ad.object module to achieve the same outcome as the attribute which stores what principals can retrieve the password is a SecurityDescriptor value which is not easy to craft in Ansible.
Fixes: https://github.com/ansible-collections/microsoft.ad/issues/123
- New Module Pull Request
microsoft.ad.service_account
=> Added microsoft.ad.service account module

tests/unit/plugins/plugin_utils/_ldap/test_certificate.py
Relax the edge cases this unit test had now that cryptography only allows valid UTF-8 sequences.
tests
=> Fix up unit test now that cryptography only allows valid strings

changelogs/fragments/141-group-empty-member.yml, plugins/module_utils/_ADObject.psm1, tests/integration/targets/group/tasks/tests.yml
Add a fix when attempting to create a group with an explicitly empty set of members. This fix also applies to any other add/set/remove attribute when the resulting value is an empty value. The error only applied when creating the AD object as the `New-AD* -OtherAttributes` parameter could not handle an empty array value.
Fixes: https://github.com/ansible-collections/microsoft.ad/issues/141
microsoft.ad.group (and others)
=> group - fix setting explicitly empty members

changelogs/fragments/membership-rename.yml, plugins/modules/membership.ps1, tests/integration/targets/membership/tasks/join_with_name_conflict.yml, tests/integration/targets/membership/tasks/main.yml, tests/integration/targets/membership/test.yml
This is for situations when joining to a domain with a `hostname` change too.
When using the `Add-Computer` cmdlet with `NewName` specified the process occurs as such:
1. Joins computer to domain using current/old hostname
2. Renames computer and AD computer account to new hostname
This generally works except in cases where the target AD computer account already exists. In such cases it will fail with the exception noted below. This is often the case when one is rebuilding/redeploying/etc an existing machine that uses a specific/static hostname.
With the changes in this PR, the process instead goes in this (IMO) more expected way:
1. Renames computer to new hostname
2. Joins computer to domain using new hostname (using the existing computer account if one is present)
- Feature Pull …
=> membership - Improve domainjoin+rename process

changelogs/fragments/ldap-msa.yml, plugins/inventory/ldap.py, tests/integration/targets/inventory_ldap/main.yml, tests/integration/targets/inventory_ldap/roles/test/tasks/main.yml
This change will filter out all managed service accounts in the default LDAP filter used with the `microsoft.ad.ldap` filter plugin. This ensures that the only objects returned as hosts are actual computer accounts and not object classes that descend from the `computer` class but are not actually computers.
=> Filter out MSA in the LDAP inventory plugin

.azure-pipelines/azure-pipelines.yml, tests/utils/shippable/windows.sh
Expands the testing matrix of the Windows connection plugins used in CI to cover all the supported connections of Windows.
testing
=> Expand connection plugins used in CI

changelogs/fragments/debug-ldap-client-doc.yml, plugins/modules/debug_ldap_client.py, tests/sanity/ignore-2.15.txt, tests/sanity/ignore-2.16.txt, tests/sanity/ignore-2.17.txt
Fixes `microsoft.ad.debug_ldap_client` documentation problem so that it
works with `ansible-doc` and the online plugin docs.
docs
=> Fix debug_ldap_client doc

.azure-pipelines/azure-pipelines.yml, tests/integration/targets/inventory_ldap/roles/setup_certificate/files/generate_cert.sh
Updates CI to test out sanity on both 2.18 and 2.19 now that devel has been bumped to a new version. Include the new sanity ignore file for 2.19 and fix up the cert generation for the LDAPS CA certificate.
=> Update CI setup

changelogs/fragments/replication-dc.yml, galaxy.yml, plugins/modules/domain_child.ps1, plugins/modules/domain_child.yml, plugins/modules/domain_controller.ps1, plugins/modules/domain_controller.yml
Adds the option `replication_source_dc` to the `microsoft.ad.domain` and `microsoft.ad.domain_controller` module that allows the caller to specify the DC used for replication when creating the domain controller.
Fixes: https://github.com/ansible-collections/microsoft.ad/issues/159
microsoft.ad.domain
microsoft.ad.domain_controller
=> Added replication_source_dc options

docs/docsite/rst/guide_ldap_inventory.rst, plugins/filter/ldap_converters.py, plugins/filter/parse_dn.yml, plugins/filter/split_dn.yml, tests/unit/plugins/filter/test_ldap_converters.py
Adds the microsoft.ad.split_dn to split an LDAP DistinguishedName into either the leaf or parent component. This allows the caller to easily retrieve either value without resorting to regex which can be complicated and prone to escaping issues.
microsoft.ad.split_dn
=> Add microsoft.ad.split_dn filter

meta/runtime.yml
The `requires_ansible` entry should have the build version and not just major.minor.
=> Fix requries_ansible version

codecov.yml
Fixes the ignore entry so it will not attempt to include the CI scripts in the coverage report.
=> Fix up codecov ignore entry for Azure CI scripts

.azure-pipelines/azure-pipelines.yml, README.md, changelogs/fragments/ansible-ver.yml, galaxy.yml, meta/runtime.yml, tests/sanity/ignore-2.15.txt
Raises the min Ansible version as 2.15 is no longer supported.
=> Raise minimum ansible version to 2.16

changelogs/fragments/laps-templating.yml, plugins/inventory/ldap.py
Makes sure the LAPS encrypted value is marked as unsafe to avoid it from being templated as a string value. This means any password value that contains valid Jinja2 sequences like `{{`, `}}``, `{%`, etc will not be treated as a template.
Fixes: https://github.com/ansible-collections/microsoft.ad/issues/194
`microsoft.ad.ldap`
=> ldap - Ensure LDAP enc value is not templated
